class OrderStatus:
    CREATED = "CREATED"
    PAID = "PAID"
    PROCESSING = "PROCESSING"
    PARTIALLY_SHIPPED = "PARTIALLY_SHIPPED"
    SHIPPED = "SHIPPED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    REFUNDED = "REFUNDED"
